description: Bad
author: Leeprky
icon: https://avatars1.githubusercontent.com/u/19844016
theme: jekyll-theme-midnight

exclude:
    - README.md
    - Gemfile

sass:
    sass_dir: /
    style: compressed
